version: "3.9"
services:

  # MySQL Server 8
  mysql:
    platform: linux/x86_64 # Needed for Mac's on the M1 chip
    image: mysql:8
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: "coolblog"
      MYSQL_ROOT_PASSWORD: "mysql"
    volumes:
      # Store the data locally
      - .db/mysql8/data:/var/lib/mysql
      # You can uncomment and it will seed the db with our prepared sql data
      - ./test-harness/tests/resources:/docker-entrypoint-initdb.d

  ## PostgreSQL
  postgresql:
    platform: linux/x86_64 # Needed for Mac's on the M1 chip
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "cborm"
      POSTGRES_USER: "cborm"
      POSTGRES_DB: "coolblog"
    ports:
      - 5432:5432
    volumes:
      - .db/postgres/data:/var/lib/postgresql/data
      - ./test-harness/tests/resources/postgresql:/docker-entrypoint-initdb.d
